<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="YoneticiPanel.aspx.cs" Inherits="Proje.YoneticiPanel" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Yönetici Sayfası</title>
</head>
<body>
        <link rel="stylesheet" href="style/cssYonetici.css" type="text/css" runat="server" />

    <form id="form1" runat="server">
        <div id="header">
            <asp:button runat="server" ID="back" Text="Geri" OnClick="back_Click" CssClass="button"></asp:button>
        </div>
        <div id="main">
            <table border="0" id="table">
                <tr><td></td><th colspan="2" class="th">Kitap Ekleme</th></tr>
                <tr>
                    <td rowspan="6">
                        
                        <asp:Image runat="server" ID="image"/></td>
                </tr>
                <tr>
                    <td>
                        <asp:FileUpload ID="fileUploader" runat="server" /></td>
                    <td>
                        <asp:Button runat="server" OnClick="imageEkle_Click" Text="Ekle" ID="imageEkle" Title="Dosya seçtikten sonra bu butona basınca kitap otomatik olarak veritabanına yüklenir." CssClass="button"></asp:Button>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:Label runat="server" ID="lblUpload" Text="" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:TextBox runat="server" ID="txtISBN"  CssClass="textbox"/></td>
                    <td>
                        <asp:TextBox runat="server" ID="txtName"  CssClass="textbox"/></td>
                </tr>
                <tr>
                    <td>
                        <asp:Button runat="server" Text="Göster" ID="btnGoster" OnClick="btnGoster_Click" Title="ISBN veya isim textbox'ına yazılan değere göre sonuçları getirir." CssClass="button"></asp:Button>
                    </td>

                    <td>
                        <asp:Button runat="server" ID="Barcode" OnClick="barcode_Click" Text="Barkod Okut" Title="Silme İşlemi ile Beraber Kullanılır" CssClass="button"/>
                        <asp:Button runat="server" Text="Sil" ID="btnSil" OnClick="btnSil_Click" Title="Textbox'a yazılı olan ISBN numarasından veya isim ile bağlantılı olan kayıtları siler." CssClass="button"></asp:Button>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:GridView ID="GridView1" runat="server" DataSourceID="KITAP" AutoGenerateColumns="False" AutoGenerateDeleteButton="true" CssClass="GridView">
                            <Columns>
                                <asp:BoundField DataField="ISBN" HeaderText="ISBN"/>
                                <asp:BoundField DataField="KITAP_ADI" HeaderText="Kitap Adı"/>
                                <asp:BoundField DataField="YAZAR" HeaderText="Yazarın Adı"/>
                                <asp:ImageField HeaderText="Kitap Kapak Fotoğrafı" DataImageUrlField="KITAP_FOTO"  ControlStyle-Height="60px">
                                </asp:ImageField>
                            </Columns>
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <%--<td>
                        
                        <asp:Button runat="server" ID="cacheSil" OnClick="cacheSil_Click" Text="Sil" Title="Yüklenmiş fotoğrafları server dosyasının içinden siler."></asp:Button>
                    </td>--%>
                </tr>
                <asp:SqlDataSource ID="KITAP" runat="server" ConnectionString="<%$ ConnectionStrings:KITAPConnectionString %>" SelectCommand="SELECT * FROM [KITAPLAR]"></asp:SqlDataSource>
                <tr><td></td><th colspan="2" class="th">Zamanı İleri Alma</th></tr>
                <tr><td></td><td>
                    <asp:TextBox runat="server"  ID="txtTime" CssClass="textbox"/></td><td>
                        <asp:button runat="server" ID="btnTime" OnClick="btnTime_Click" Text="İleri Al" CssClass="button"></asp:button>
                    </td></tr>
                <tr><td></td><th colspan="2" class="th">Kullanıcı-Kitap Tablosu</th></tr>
                <tr><td></td><td colspan="2">
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource1" CssClass="GridView">
                        <Columns>
                            <asp:BoundField DataField="KULLANICI_ID" HeaderText="Kullanıcının ID'si" SortExpression="KULLANICI_ID" />
                            <asp:BoundField DataField="KITAP_ID" HeaderText="Kitabın ID'si" SortExpression="KITAP_ID" />
                            <asp:BoundField DataField="KITAP_SURE" HeaderText="Kitap Süresi" SortExpression="KITAP_SURE" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:KITAPConnectionString %>" SelectCommand="SELECT * FROM [KITAPSURE]"></asp:SqlDataSource>
                    </td></tr>
            </table>
        </div>
    </form>
</body>
</html>
